name: workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Print .NET SDK version
      run: dotnet --version

    - name: Generate GitHub App Token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Debug GitHub App Token
      run: |
        TOKEN="${{ steps.generate_token.outputs.token }}"
        MASKED_TOKEN=$(echo "$TOKEN" | sed 's/./*/g')
        echo "Generated token: $MASKED_TOKEN"

    - name: Clear GitHub Actions Runner Cache
      run: rm -rf ~/.npm ~/.nuget ~/.cargo ~/.dotnet

    - name: Nuget set access (Debug Token)
      run: |
        dotnet nuget remove source github-utils || true
        dotnet nuget add source --username "x-access-token" --password "${{ steps.generate_token.outputs.token }}" \
        --store-password-in-clear-text --name github-utils "https://nuget.pkg.github.com/garethbirduk/index.json"
        dotnet nuget list source

    - name: Verify NuGet Source
      run: dotnet nuget list source

    - name: Test Package Access with Token
      run: |
        curl -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/users/garethbirduk/packages/nuget/GradientSoftware.Utils/versions"

    - name: Restore dependencies (with debug)
      run: |
        dotnet restore || echo "NuGet restore failed! Check authentication."

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Install modules
      run: yarn --prefer-offline


    - name: Test and generate coverage report
      run: |
        dotnet test --configuration Release --no-build GoogleLibrary.Test/GoogleLibrary.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" --verbosity normal
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:GoogleLibrary.Test/coverage.opencover.xml" "-targetdir:./coverage/" "-reporttypes:Badges;Html;TextSummary"

    - name: Upload Test Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage/

    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v1
            
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      if: github.ref == 'refs/heads/main'
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: ./GoogleLibrary.Test/coverage.opencover.xml
        gist-filename: code-coverage.json
        gist-id: a2dad97892401a59b47ed06b9e80a86f
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}       

    - name: Print badge data
      if: github.ref == 'refs/heads/main'    
      run: echo "Badge data ${{steps.test_step.outputs.badge}}"

    - name: Nuget deploy Packages
      if: github.ref == 'refs/heads/main'
      run: |
        dotnet nuget push ./GoogleLibrary/bin/Release/**/*.nupkg --source "github" --api-key ${{ secrets.GH_APIKEY }} --skip-duplicate
        dotnet nuget push ./GoogleServices/bin/Release/**/*.nupkg --source "github" --api-key ${{ secrets.GH_APIKEY }} --skip-duplicate